# Generated by Django 5.2.4 on 2026-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Описание'),
        ),
    ]
