# Generated by Django 5.2.4 on 2026-04-13 19:56

from django.db import migrations, models

import core.service
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_skill_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.service.user_avatar_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, null=True, validators=[core.validators.validate_github_user_url], verbose_name='Ссылка на GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[core.validators.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
    ]
